[[redirects]]
  from = "/build/base.min.css"
  to = "https://legocsslibrary.netlify.app/build/base.min.css"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/build/component.min.css"
  to = "https://legocsslibrary.netlify.app/build/component.min.css"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/build/demo.min.css"
  to = "https://legocsslibrary.netlify.app/build/demo.min.css"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/build/lego.min.css"
  to = "https://legocsslibrary.netlify.app/build/lego.min.css"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/build/reset.min.css"
  to = "https://legocsslibrary.netlify.app/build/reset.min.css"
  status = 200
  force = true
  headers = {X-From = "Netlify"}